### ISSUE TITLE
Use native Promises when possible

### ISSUE THREAD

**Issue by jganetsk** [cujojs/when#248]
If I'm to understand, a trusted promise is nothing more than an object that we know is an A+ Promise.

Therefore, native promises could therefore be considered trusted promises.

So, perhaps when.js should detect when native promises are present, and construct them instead of using the Promise constructor?

http://www.html5rocks.com/en/tutorials/es6/promises/

I think this is fairly straightforward to implement. The only snafu is that the native Promise constructor looks different than the when.js Promise constructor.

**Comment by sompylasar** [comment]
> I think we're still fairly far from being able to rely on the builtin Promise prototype. The current generation of implementations are orders of magnitude slower than the current generation of fastest implementations (when.js, bluebird, rsvp).

@briancavalier After 3+ years, would you re-evaluate this decision? Thank you.
