### ISSUE TITLE
When/Node doesn't liftAll on Redis

### ISSUE THREAD

**Issue by ghost** [cujojs/when#294]
I'm just starting in with when.js, so I'm 90% sure I'm just doing something wrong, but for the life of me I can't figure it out (or find it mentioned elsewhere).  Please point me to a better forum for asking for help if I'm in the wrong place.

My problem is that I'm trying to use when.js with the [redis module](https://github.com/mranney/node_redis) to promis-ify its API.  However, when I follow the guide for [node.liftAll](https://github.com/cujojs/when/blob/master/docs/api.md#nodeliftall), it appears as though all the methods on the returned object do exactly what the methods did on the original.

Here are some repro steps and example code:
## STEPS
1. Install Redis server locally (e.g., `apt-get install redis`)
2. Install "when" and "redis" node modules (e.g., "npm install redis && npm install when")
3. Drop this file on your system as `example.js`:

``` js
when = require("when/node");
redis = require("redis");

client = redis.createClient(6379, "127.0.0.1");
client_when = when.liftAll(client);

console.log("client.get === client_when.get ?  " + (client.get === client_when.get));

process.exit();
```
1. Run it (e.g., `node example.js`)
### EXPECTED

The program will output `client.get === client_when.get ?  false` because the `get` method has been lifted on one, but not on the other.
### ACTUAL

The program outputs `client.get === client_when.get ?  true`.  Further, if you attempt to actually call the `get` method on either object, they both function exactly like the original method.

**Comment by bertho-zero** [comment]
For liftAll commands of redis you can do:

```js
"use strict";

const wn = require( 'when/node' );
const commands = require( 'redis-commands' ).list;

module.exports = client => {

  for ( const name of commands ) {

    client[ name + 'Async' ] = wn.lift( client[ name ] ).bind( client );

  }

  return client;

}
```

And use it as:

```js
const client = redis.createClient();

promisifyRedis( client );
```
