### ISSUE TITLE
Paths for lib modules not resolving

### ISSUE THREAD

**Issue by adamjgrant** [cujojs/when#359]
I'm getting the errors

```
Cannot find module './makePromise' from '/Users/x/Sites/y/node_modules/when/es6-shim'
Cannot find module './Scheduler' from '/Users/x/Sites/y/node_modules/when/es6-shim'
Cannot find module './async' from '/Users/x/Sites/y/node_modules/when/es6-shim'
Cannot find module './Queue' from '/Users/x/Sites/y/node_modules/when/es6-shim'
Cannot find module '../timer' from '/Users/x/Sites/y/node_modules/when/es6-shim'
```

At first I thought this was something wrong with my implementation.

Then, I noticed in the [Promise.js](https://github.com/cujojs/when/blob/master/es6-shim/Promise.js) file, the references to the modules don't appear to be correct.

```
var makePromise = require('./makePromise');
var Scheduler = require('./Scheduler');
var async = require('./async');

return makePromise({
    scheduler: new Scheduler(async)
});
```

They reference the current directory, which is not /lib. Shouldn't they be 

```
../lib/makePromise
```

?

**Comment by teohhanhui** [comment]
Any workaround for this? My r.js build is failing for the same reason...

**Comment by briancavalier** [comment]
@teohhanhui As a workaround, you can either use the [`when/es-shim/Promise.browserify-es6` module](https://github.com/cujojs/when/blob/master/es6-shim/Promise.browserify-es6.js) directly (that is, the *non*-browserified shim), or create a simple module that does something similar and use that.

**Comment by jrburke** [comment]
For using the browserified version of when.js in the r.js optimizer: if the browserify dependency chain upgrades to https://github.com/ForbesLindesay/umd version 3 (which contains [this change](https://github.com/ForbesLindesay/umd/pull/12)) and if r.js 2.1.16 is used (released within the next day, and contains [this change](https://github.com/jrburke/r.js/issues/733)), then it should be consumable by r.js.

**Comment by briancavalier** [comment]
Hey @jrburke, thanks a bunch for the heads up!  Seems like we just need to sit tight until a new version of browserify is available (one that depends on umd >= 3.0.0).  Then we can release a new when.js with an es6 shim built using that new version.

**Comment by ajkochanowicz** [comment]
I'll be the first to wear the dunce hat and say this is all fantastically
confusing.

**Comment by briancavalier** [comment]
@ajkochanowicz I agree it's confusing.  Sorry about that :(  However, it's really a scenario that should have worked all along.  The confluence of when's UMD format, browserify (via it's `umd` lib dependency), and r.js is what causes it to fail.  It was no particular fault of any one of those, but rather likely the fact that it hadn't been common to use r.js to do builds containing pre-browserified files.

The good news is that once browserify updates it's dependencies, it should Just Work.

**Comment by ajkochanowicz** [comment]
That's great. I understand it's a difficult problem to solve and appreciate your hard work.
