### ISSUE TITLE
Calling `then` on a fulfilled promise not returning

### ISSUE THREAD

**Issue by ghost** [cujojs/when#362]
I'll start by saying this is almost certainly something I'm doing wrong, but I can neither figure out what it is, nor find any other resource which helps make it clear.

I have a simple object which provides an interface to a remote service (Redis, in this case).  It's constructor accepts a connection object (or a promise of one), wraps it in a promise, and keeps it in an instance variable.  Later, when its various methods are called, each will first call `then` on the connection promise created in the constructor, and when it fulfills, proceeds to do its work with the database.

This generally works without any issues at all, but I'm now seeing one particular test fail, and I can't figure out why.  The problem is that when I run this code:

``` coffeescript
    findInIndex: (name, values)->
        key = @_makeIndexKey name, values
        logger.debug "waiting for: #{_.pp(@connecting.inspect())}..."
        @connecting
            .then(
                ((c)-> logger.debug "connected.  looking for key: #{key}..."; c.smembers key),
                ((e)-> logger.debug "rejected: #{e}")
            )
            .then (result)->
                logger.debug -> "got result: #{_.pp(result)}"
                return result
```

The last thing which prints is: `waiting for: {state:fulfilled, value:RedisClient...` and then the test simply hangs.  In particular, neither the `onFulfilled` or `onRejected` functions are run.

Given that `@connecting` was reported as already being fulfilled, I'd have expected the first call to `then` to invoke the `onFulfilled` callback immediately.  I'm completely unable to account for it hanging, nor can I even figure out how to start debugging the issue.

Any thoughts?

**Comment by meeshaT** [comment]
Hi, I am facing similar issue.

**Comment by meeshaT** [comment]
First function that gets called.
`downloadN: function downloadN(scr) {

    /* istanbul ignore if */
    if (!scr.loc) {
      return _promise2.default.reject(new Error('`scr.loc` is required'));
    }

    var shunt = new _events.EventEmitter();
    var promise = this._fetchDownloadUrlN(scr);

    (0, _common.proxyEvents)(shunt, promise);

    alert("Conversation " + JSON.stringify(promise));
    return promise
  }`
Second func call
`fetchDownloadUrlN: function _fetchDownloadUrlN(scr) {
    var _this2 = this;

    this.logger.info('encryption: retrieving download url for encrypted file');

    if (process.env.NODE_ENV !== 'production' && scr.loc.includes('localhost')) {
      this.logger.info('encryption: bypassing webex files because this looks to be a test file on localhost');

      return _promise2.default.resolve(scr.loc);
    }

    return this.request({
      method: 'POST',
      service: 'files',
      resource: 'download/endpoints',
      body: {
        endpoints: [scr.loc]
      }
    }).then(function (res) {
      var url = scr.loc;
      alert("_fetchDownloadUrlN!!! " + JSON.stringify(_this2._callDownloadUrl(url)));
      return _this2._callDownloadUrl(url)
    });
  }`

Third func call 
`_callDownloadUrl: function _callDownloadUrl(uri){
    var _this2 = this;
    return this.request({
      method: 'GET',
      uri: 'https://api.ciscospark.com/v1/organizations',
    }).then(function (res) {
      alert("_callDownloadUrl" + JSON.stringify(_this2._helperFunction(uri)));
      return _this2._helperFunction(uri);
    }).catch((err) => {
      alert("Error!!! " + JSON.stringify(err));
      return err;
    });
  }`

Fourth function call
`_helperFunction: function _helperFunction(uri){
    var options = {
      method: 'GET',
      uri: uri,
      responseType: 'buffer'
    };

    var ret = _this.request(options);

    (0, _common.transferEvents)('progress', options.downloadN, shunt);

    return ret.then(function (res) {
      alert("_helperFunction " + JSON.stringify(res));
    return _this.decryptBinary(scr, res.body);
  })
  (0, _common.proxyEvents)(shunt, promise);
  }`

Final promise that I am returning from downloadN is coming empty JSON. Am I missing something.
