### ISSUE TITLE
IE8 error using Object.create in TimeoutError

### ISSUE THREAD

**Issue by kyle-dorman** [cujojs/when#447]
Hi, I am getting an IE8 error due to TimeoutError setting its prototype by calling Object.create which doesn't seem to be supported in IE8.

**Comment by unscriptable** [comment]
Hey @kyle-dorman!

You will need to use an ES5 polyfill library such as [poly.js](https://github.com/cujojs/poly) or [es5-shim](https://github.com/es-shims/es5-shim) to use when.js with IE8.  If you need some help getting either of those to work with your loader, just reopen this issue and we'll try to give you a hand. :)

-- John
