### ISSUE TITLE
when.js + webpack + sinon.useFakeTimers()

### ISSUE THREAD

**Issue by KidkArolis** [cujojs/when#449]
I'm running into this issue
https://github.com/webpack/node-libs-browser/issues/20

Do you think the isNode() detection could be improved in when.js somehow so that Mutation Observers are used even if webpack injects a fake window.process?

On the other hand, this would only fix this issue for modern browsers..

**Comment by KidkArolis** [comment]
Ok. Actually. I think it's all fine now. :-S

**Comment by KidkArolis** [comment]
Oh well.

**Comment by KidkArolis** [comment]
Nope, the issue is back.

**Comment by KidkArolis** [comment]
This is how bluebird does the `isNode` check https://github.com/petkaantonov/bluebird/blob/master/src/util.js#L284-L285

**Comment by briancavalier** [comment]
Heh, thanks @KidkArolis.  I should have time to look into this over the weekend.
