### ISSUE TITLE
Is there a way to convert Jquery Promise to When Promise

### ISSUE THREAD

**Issue by Maatary** [cujojs/when#453]

**Comment by campersau** [comment]
You can just wrap other promises with `when(otherPromise)`
For example:
```js
var whenPromise = when(jQuery.ready.promise());
```

You can read more about it here: https://github.com/cujojs/when/wiki/when#non-compliant-promises

**Comment by briancavalier** [comment]
Thanks for jumping in @campersau.  That exactly right, and is the simplest way.  Also info here: https://github.com/cujojs/when/blob/master/docs/api.md#when

Note that `when(x)` and `when.resolve(x)` basically do the same thing, as does `Promise.resolve(x)` if you're using [the ES6 Promise shim](https://github.com/cujojs/when/blob/master/docs/es6-promise-shim.md#es6-promise-shim).

Closing, but please feel free to continue to discuss, or reopen if you need, @Maatary
