### ISSUE TITLE
Grunt fail to resolve dependencies and combine files

### ISSUE THREAD

**Issue by podlipensky** [cujojs/when#456]
I installed whenjs via bower and added it to my require config:
```
{
        name: 'when',
        location: '../../../bower_components/when',
        main: 'when'
}
```
Now I'm trying to combine everything into one file using grunt and I get this error:
```
Tracing dependencies for: common/main
{ [Error: Error: Non-existent context variable used in file project/tmp/js/../../../bower_components/when/lib/Scheduler.js: "run:function"
Make sure you have the variable both in the server manifest and default.yaml file.
]
  originalError:
   [Error: Non-existent context variable used in file project/tmp/js/../../../bower_components/when/lib/Scheduler.js: "run:function"
   Make sure you have the variable both in the server manifest and default.yaml file.] }
Fatal error: Project "project" encountered an error.
```

Any help will be appreciated

**Comment by briancavalier** [comment]
Hi @podlipensky, a few quick questions that may help us figure out what's going on.

What grunt plugin are you using to build?  When.js works well with r.js, browserify, web pack, and others, so maybe it's something about your particular configuration.

When you say "require config", do you mean RequireJS config?  If so, did you configure when.js as a package or a path?  Looking at the config snippet you pasted, it appears you used a package ([which is correct](https://github.com/cujojs/when/blob/master/docs/installation.md#amd)), but I just want to verify.

Thanks!

**Comment by podlipensky** [comment]
nvm, looks like it was interfering with another module. Thanks for response anyway

**Comment by briancavalier** [comment]
No prob, glad you figured it out!
