### ISSUE TITLE
Do not use git in package.json

### ISSUE THREAD

**Issue by artem-malko** [cujojs/when#470]
Hi.
Is it possible to not use git here: https://github.com/cujojs/when/blob/master/package.json#L60
It is a problem, cause I can't install this package without git in my OS.

**Comment by briancavalier** [comment]
Hey @artem-malko, yeah, now that [poly is published to npm](https://github.com/cujojs/poly/releases), we could switch to that.  I'll try it out in a branch soon.

Poly is only used for unit testing when.js in browsers (on saucelabs).  Is it an option for you to `npm install --production` in the mean time?

**Comment by artem-malko** [comment]
@briancavalier hi!
No, I can't do it, cause when is used as dep in gulp-less and gulp-stylus. So, I'll be waiting for new release.
Thank you.

**Comment by briancavalier** [comment]
@artem-malko Understood, thanks for clarifying.  I should have time to send a PR for this tonight.

**Comment by artem-malko** [comment]
@briancavalier could you write to me (or just write here) after all work has been done?

**Comment by briancavalier** [comment]
Sure, I'll ping you in the PR so you can follow it.

**Comment by artem-malko** [comment]
Thank you a lot)

**Comment by briancavalier** [comment]
@artem-malko I just published [3.7.4](https://github.com/cujojs/when/releases/tag/3.7.4) which includes this change.  I hope it helps!

**Comment by artem-malko** [comment]
@briancavalier it is really helpful)
