### ISSUE TITLE
when/poll has no (default) timeout

### ISSUE THREAD

**Issue by jiaweihli** [cujojs/when#478]
Adding a reasonable default timeout, and a timeout argument would make this even more useful!

**Comment by jiaweihli** [comment]
[promise.timeout](https://github.com/cujojs/when/blob/master/docs/api.md#promisetimeout) handles this.

**Comment by briancavalier** [comment]
Hey @jiaweihli!  Yep, your polling function can return promises with a timeout.  Cheers!
