### ISSUE TITLE
JSPM build (SystemJS builder) failing on when@3.7.7

### ISSUE THREAD

**Issue by dananichev** [cujojs/when#483]
```
       npm:when@3.7.7/when.js


err  Error: Unexpected token: punc ()) (line: 4539, col: 16, pos: 153518)
```

**Comment by briancavalier** [comment]
Hi @dananichev.  I need your help in understanding more about this error.  Please provide more information and steps to reproduce it.  Thanks!

**Comment by dananichev** [comment]
@briancavalier my bad. Everything is fine with ```when```. It was custom interceptor for ```rest.js```. Sorry.

**Comment by briancavalier** [comment]
No worries. Glad you figured it out.
