### ISSUE TITLE
npm install ! has errors

### ISSUE THREAD

**Issue by imnot2** [cujojs/when#495]
D:\workspace\axis-ui-shared\bower_components\when\node_modules\contextify>if not defined npm_config_node_gyp (node "C:\Users\bigui.ding\AppData\Roaming\npm\node _modules\npm\bin\node-gyp-bin\....\node_modules\node-gyp\bin\node-gyp.js" rebu ild ) else (node "" rebuild )
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
contextify.cc
c:\users\bigui.ding\.node-gyp\6.9.2\include\node\v8.h(345): error C2988: unrecog                                                                                                    nizable template declaration/definition [D:\workspace\axis-ui-shared\bower_compo                                                                                                    nents\when\node_modules\contextify\build\contextify.vcxproj]

**Comment by unscriptable** [comment]
Hey @imnot2.  From the error, this looks more like a contextify problem, doesn't it?  Have you asked for help [over there](https://github.com/brianmcd/contextify/issues)?
